source :rubygems

gem "rack"
gem "sinatra"
gem "haml"
gem "activesupport", :require => "active_support/all"
gem "activerecord"
gem "sqlite3"
gem "rack_csrf"
gem "rake"
gem "shotgun"
gem "redcarpet"
gem "coderay"
gem "sinatra-contrib"
gem "sinatra-activerecord", :require => "sinatra/activerecord"
gem "bundler"
gem "sass"
